const ROUTES = [
  '',
  'bathroom-with-a-view',
  'beautiful-one',
  'colors',
  'dark-night',
  'growing-in-time',
  'idk-yet',
  'inside-light',
  'lie-down-with-me',
  'madeline',
  'peripheral',
  'sources',
  'start',
  'territories',
  'transient-ecstasy',
  'wasp-and-orchid',
  'web',
  'yayayayayaya',
];
export default ROUTES;
